apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-microprofile
  labels:
    app: jakartaee-microprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jakartaee-microprofile
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jakartaee-microprofile
    spec:
      containers:
      - name: jakartaee-microprofile
        image: us-east1-docker.pkg.dev/nice-ocean-419714/devnexus/devnexus-workshop-app
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1G"
            cpu: "500m"
        ports:
        - containerPort: 9080
        env:
        - name: HUGGING_FACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: huggingfacekey
              key: HUGGING_FACE_API_KEY
        
